# Generated by Django 5.2.8 on 2025-11-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Radhirra', '0005_category_created_at_alter_category_name_and_more'),
    ]

    operations = [
    ]
