# Generated by Django 5.2.8 on 2025-12-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Radhirra', '0009_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
