# Generated by Django 5.2.8 on 2025-12-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Radhirra', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sleeve',
            field=models.CharField(blank=True, choices=[('sleeveless', 'Sleeveless'), ('short', 'Short'), ('3/4', '3/4')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sleeve',
            field=models.CharField(blank=True, choices=[('sleeveless', 'Sleeveless'), ('short', 'Short'), ('3/4', '3/4')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, null=True),
        ),
    ]
